<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Dish;

class DishSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $dishes = [
            // Pizza Palace - vendor_id: 1
            [
                'vendor_id' => 1,
                'category_id' => 1, // Pizzas
                'name' => 'Pizza Margherita',
                'description' => 'Pizza classique avec sauce tomate, mozzarella et basilic',
                'price' => 12.99,
                'image' => 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=400',
                'is_available' => true,
                'is_popular' => true,
                'rating' => 4.7,
                'review_count' => 45,
                'order_count' => 120,
                'ingredients' => ['Sauce tomate', 'Mozzarella', 'Basilic', 'Huile d\'olive'],
                'preparation_time' => 15,
                'calories' => 285,
                'cuisine_type' => 'Italienne',
                'is_vegetarian' => true,
                'is_vegan' => false,
                'is_gluten_free' => false,
            ],
            [
                'vendor_id' => 1,
                'category_id' => 1,
                'name' => 'Pizza Pepperoni',
                'description' => 'Pizza avec pepperoni, mozzarella et sauce tomate',
                'price' => 14.99,
                'image' => 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400',
                'is_available' => true,
                'is_popular' => true,
                'rating' => 4.5,
                'review_count' => 38,
                'order_count' => 95,
                'ingredients' => ['Sauce tomate', 'Mozzarella', 'Pepperoni'],
                'preparation_time' => 18,
                'calories' => 320,
                'cuisine_type' => 'Italienne',
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => false,
            ],
            [
                'vendor_id' => 1,
                'category_id' => 1,
                'name' => 'Pizza Quatre Fromages',
                'description' => 'Pizza avec quatre fromages différents',
                'price' => 16.99,
                'image' => 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400',
                'is_available' => true,
                'is_popular' => false,
                'rating' => 4.3,
                'review_count' => 22,
                'order_count' => 45,
                'ingredients' => ['Mozzarella', 'Gorgonzola', 'Parmesan', 'Ricotta'],
                'preparation_time' => 20,
                'calories' => 350,
                'cuisine_type' => 'Italienne',
                'is_vegetarian' => true,
                'is_vegan' => false,
                'is_gluten_free' => false,
            ],

            // Burger House - vendor_id: 2
            [
                'vendor_id' => 2,
                'category_id' => 2, // Burgers
                'name' => 'Classic Burger',
                'description' => 'Burger classique avec steak, laitue, tomate et oignon',
                'price' => 9.99,
                'image' => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
                'is_available' => true,
                'is_popular' => true,
                'rating' => 4.4,
                'review_count' => 67,
                'order_count' => 180,
                'ingredients' => ['Steak de bœuf', 'Laitue', 'Tomate', 'Oignon', 'Fromage'],
                'preparation_time' => 12,
                'calories' => 450,
                'cuisine_type' => 'Américaine',
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => false,
            ],
            [
                'vendor_id' => 2,
                'category_id' => 2,
                'name' => 'Veggie Burger',
                'description' => 'Burger végétarien avec galette de légumes',
                'price' => 11.99,
                'image' => 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=400',
                'is_available' => true,
                'is_popular' => false,
                'rating' => 4.1,
                'review_count' => 34,
                'order_count' => 60,
                'ingredients' => ['Galette de légumes', 'Laitue', 'Tomate', 'Oignon'],
                'preparation_time' => 10,
                'calories' => 320,
                'cuisine_type' => 'Américaine',
                'is_vegetarian' => true,
                'is_vegan' => true,
                'is_gluten_free' => false,
            ],

            // Sushi Master - vendor_id: 3
            [
                'vendor_id' => 3,
                'category_id' => 3, // Sushis
                'name' => 'California Roll',
                'description' => 'Rouleau californien avec crabe, avocat et concombre',
                'price' => 8.99,
                'image' => 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400',
                'is_available' => true,
                'is_popular' => true,
                'rating' => 4.6,
                'review_count' => 89,
                'order_count' => 150,
                'ingredients' => ['Riz', 'Crabe', 'Avocat', 'Concombre', 'Nori'],
                'preparation_time' => 8,
                'calories' => 180,
                'cuisine_type' => 'Japonaise',
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => true,
            ],
            [
                'vendor_id' => 3,
                'category_id' => 3,
                'name' => 'Salmon Nigiri',
                'description' => 'Nigiri au saumon frais',
                'price' => 12.99,
                'image' => 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400',
                'is_available' => true,
                'is_popular' => true,
                'rating' => 4.8,
                'review_count' => 76,
                'order_count' => 120,
                'ingredients' => ['Riz', 'Saumon', 'Wasabi'],
                'preparation_time' => 5,
                'calories' => 120,
                'cuisine_type' => 'Japonaise',
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => true,
            ],

            // Green Garden - vendor_id: 4
            [
                'vendor_id' => 4,
                'category_id' => 4, // Salades
                'name' => 'César Salad',
                'description' => 'Salade César avec poulet grillé et parmesan',
                'price' => 13.99,
                'image' => 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400',
                'is_available' => true,
                'is_popular' => true,
                'rating' => 4.3,
                'review_count' => 45,
                'order_count' => 85,
                'ingredients' => ['Laitue romaine', 'Poulet grillé', 'Parmesan', 'Croûtons'],
                'preparation_time' => 10,
                'calories' => 280,
                'cuisine_type' => 'Américaine',
                'is_vegetarian' => false,
                'is_vegan' => false,
                'is_gluten_free' => false,
            ],
            [
                'vendor_id' => 4,
                'category_id' => 4,
                'name' => 'Greek Salad',
                'description' => 'Salade grecque avec feta et olives',
                'price' => 11.99,
                'image' => 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400',
                'is_available' => true,
                'is_popular' => false,
                'rating' => 4.2,
                'review_count' => 28,
                'order_count' => 40,
                'ingredients' => ['Tomates', 'Concombre', 'Feta', 'Olives', 'Oignon'],
                'preparation_time' => 8,
                'calories' => 220,
                'cuisine_type' => 'Grecque',
                'is_vegetarian' => true,
                'is_vegan' => false,
                'is_gluten_free' => true,
            ],

            // Sweet Dreams - vendor_id: 5
            [
                'vendor_id' => 5,
                'category_id' => 5, // Desserts
                'name' => 'Tiramisu',
                'description' => 'Tiramisu classique italien',
                'price' => 7.99,
                'image' => 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400',
                'is_available' => true,
                'is_popular' => true,
                'rating' => 4.7,
                'review_count' => 56,
                'order_count' => 95,
                'ingredients' => ['Mascarpone', 'Café', 'Biscuits', 'Cacao'],
                'preparation_time' => 5,
                'calories' => 320,
                'cuisine_type' => 'Italienne',
                'is_vegetarian' => true,
                'is_vegan' => false,
                'is_gluten_free' => false,
            ],
            [
                'vendor_id' => 5,
                'category_id' => 5,
                'name' => 'Chocolate Cake',
                'description' => 'Gâteau au chocolat moelleux',
                'price' => 6.99,
                'image' => 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400',
                'is_available' => true,
                'is_popular' => true,
                'rating' => 4.5,
                'review_count' => 42,
                'order_count' => 75,
                'ingredients' => ['Chocolat noir', 'Farine', 'Œufs', 'Sucre', 'Beurre'],
                'preparation_time' => 3,
                'calories' => 380,
                'cuisine_type' => 'Française',
                'is_vegetarian' => true,
                'is_vegan' => false,
                'is_gluten_free' => false,
            ],
        ];

        foreach ($dishes as $dish) {
            Dish::create($dish);
        }
    }
} 